---
# tasks file for letsencrypt
- name: add letsencrypt PPA
  apt_repository:
    repo: 'ppa:certbot/certbot'
    state: present

- name: install certbot
  apt:
    name: certbot
    state: present
    update_cache: true

- name: check if cert already exists
  stat: path=/etc/letsencrypt/live/{{ letsencrypt_hostname }}/fullchain.pem
  register: cert

- name: get the cert for the domain
  shell: "certbot certonly --standalone -d '{{ letsencrypt_hostname }}' --email {{ letsencrypt_email }} --non-interactive --agree-tos"
  when: cert.stat.exists == False
